### ISSUE TITLE
Leverage Generative AI across Open Food Facts (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ai#289]
### What
- Investigate writing a script to augment taxonomy files using the ChatGPT API
- Prompts like: 
`translate this in as many languages as possible: en:PE - Polyethylene, Polyethylene`
`can you format the list with the format "2 letter langcode:translation"`
"Summarise in 3 sentences the production of material X, how it is used in food packaging and and how it is recycled"
might be useful
- This would be particularly useful for Open Products Facts 26000 category system (from the UNSPC) which is currently in English, without synonyms, without links to Wikidata, and without translations
- Given the sheer amount of content to review, we'd need a system to do that entry per entry, create a git branch, commit, and create a PR.
- @alexgarel has proposed a Taxonomy Editor integration, but that's longer term

### Where
- Taxonomy Editor (https://github.com/openfoodfacts/taxonomy-editor/issues/233)
  - Schema definition: https://openfoodfacts.slack.com/archives/C03MEM1CMJ4/p1676631826269169
  - Subcategories: https://openfoodfacts.slack.com/files/U02KZKKA5/F04Q4ENDBR8/image.png
- IDE used for taxonomy edition
- Odoo Connect (https://twitter.com/PaulUheet/status/1630203943140687874?t=qbwmOWfIu9ZNIWYBk0bgYw)
- Mobile App: https://github.com/openfoodfacts/smooth-app/issues/5009

### How
- Short term: Using the closed/paid for ChatGPT Python API
- Migrating to a fully open stack ASAP

### Leverage Generative AI across Open Food Facts (tracker)
- [ ] https://github.com/openfoodfacts/taxonomy-editor/issues/233
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/304
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/305
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/307

### LLMs for data quality
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/297

### LLMs for Data Quality
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/342

### LLMs for predictions/analysis
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/291
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/292
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/293

### LLMs for data extraction
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/309
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/306
- [x] https://github.com/openfoodfacts/openfoodfacts-ai/issues/314
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/312

### LLMs for highly structured content generation
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/296
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/294
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/298
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/295
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/290
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/288

### LLMs for semi-structured/unstructured content generation
- [ ] Use LLMs to summarize labels
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/300
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/303
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/299

### LLMs for Open Food Facts teams productivity
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/301
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/302

### Ensuring Open Food Facts is leveraged by LLMs/stays relevant
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/8447
