### ISSUE TITLE
Use LLMs to find subcategories for taxonomies

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ai#295]
### What
- Use LLMs to find subcategories for taxonomies

`Provide a bullet point list of subcategories for "Inflatable toys"`

- Inflatable pools
- Inflatable water slides
- Inflatable bouncers and castles
- Inflatable rafts and boats
- Inflatable beach balls
- Inflatable air mattresses
- Inflatable loungers and chairs
- Inflatable snow tubes
- Inflatable kayaks
- Inflatable pool toys (dartboards, basketball hoops, etc.)

### Tasks/Brainstorm

- [ ] Writing the prompt to get a good output
- [ ] Integrating within the front UI of the Taxonomy Editor
- [ ] Adding an API route calling the Gemini API (or something else eventually) in the Taxonomy Editor backend
- [ ] Adding a cache system or precomputing everything ?

_Originally posted by @teolemon in https://github.com/openfoodfacts/openfoodfacts-ai/discussions/272#discussioncomment-4904717_

### Part of
- #289

**Comment by baslia** [comment]
Hey, do you still need help with that?
I can run open source reasoning models on my machine, so that could help to define the different subcategories for non food products.

**Comment by teolemon** [comment]
It's not clear what the new url should be. Here are matches of the current URL for the record. https://github.com/search?q=repo%3Aopenfoodfacts%2Fopenfoodfacts-server%20lilo&type=code
Either we can find the new url, or we might scrape the promo. Unclear if the programme is still going.

**Comment by baslia** [comment]
> It's not clear what the new url should be. Here are matches of the current URL for the record. https://github.com/search?q=repo%3Aopenfoodfacts%2Fopenfoodfacts-server%20lilo&type=code Either we can find the new url, or we might scrape the promo. Unclear if the programme is still going.

Not sure if I totally understood this comment, but my understanding is that this issue is to build the taxonomy for non-food products using a reasoning model. Is that also to run the inference too?

**Comment by teolemon** [comment]
just a copy paste error 😅 on the wrong repo
I have seeded the taxonomy for non-food products using the Google Product Taxonomy. 
This would be more having a system able to provide children to existing categories.
I've added a few tasks to the initial issue to clarify.

**Comment by baslia** [comment]
Makes sense, thank you for clarifying!
I can start working on a script & prompt to suggest the subcategories.
Do you have the current taxonomy?
